### PR TITLE
Add Servo

### PR DESCRIPTION
**Pull request by mrego**
It'd be great to have also Servo in this website.

Let me know if we need something else here, other than adding the new repo to the `repositories.json5`.

### CODE REVIEW

**Comment by ArthurSonzogni** [comment]
Thanks you! That's a good idea.

> Let me know if we need something else here, other than adding the new repo to the repositories.json5.

I think that's it if we are lucky.

Maybe Github action will have enough time to do the initial import before timing out. If it doesn't, I will have to do it locally first.

**Comment by ArthurSonzogni** [comment]
Pending initial import:
https://github.com/ArthurSonzogni/CommitTracker/actions/runs/11357447303

**Comment by ArthurSonzogni** [comment]
I think it only imported 2500 patches. Probably because several patches have the same timestamp and the current script stop the import after encountering too many commits with the same timestamp.

I will do a local import later during the week.

**Comment by ArthurSonzogni** [comment]
It looks like Github is having issues with the `servo` repository. Unsure why.

>            "message": "Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `D1A6:35A463:29BA6A0:2A10378:670F30CE` when reporting this issue."

**Comment by mrego** [comment]
If I can help somehow, please let me know. Thanks for merging it.

**Comment by ArthurSonzogni** [comment]
Everything has been fixed. Cool to see data about Servo!

**Pull request merged**
